
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hiring;

import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import java.sql.*;
import java.awt.*;
import java.awt.print.PrinterException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.text.*;
import net.proteanit.sql.DbUtils;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import java.awt.Graphics;
import java.awt.Toolkit;
import java.awt.image.RenderedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import org.hsqldb.rights.User;

public class Applicant_Frame extends javax.swing.JFrame {

    private ApplicantBLL applicantBLL;
    private String city, job, cv;
    private Connection con;
    private Statement st;
    private PreparedStatement pst;

    public Applicant_Frame(Connection con, ApplicantBLL applicantbll) {

        this();
        this.con = con;
        this.applicantBLL = applicantbll;
    }

    public Applicant_Frame() {
        initComponents();
        try {

        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ADDAPPLICANT = new javax.swing.JButton();
        UPDATEApplicant = new javax.swing.JButton();
        idtxt = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        CVtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1Applicant = new javax.swing.JTable();
        CV = new javax.swing.JButton();
        jobcomb = new javax.swing.JComboBox<>();
        Citycomb = new javax.swing.JComboBox<>();
        SHOWALLAPPLICANT = new javax.swing.JButton();
        SHOWAPPLICANTBYID = new javax.swing.JButton();
        DeleteApplicant2 = new javax.swing.JButton();
        mailtxt1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 255));
        setIconImages(null);
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(84, 142, 211));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Applicant");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1300, 10, 170, -1));

        jButton4.setBackground(new java.awt.Color(84, 142, 211));
        jButton4.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Home");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, -1, 50));

        jButton2.setBackground(new java.awt.Color(84, 142, 211));
        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1560, 100));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(84, 142, 211));
        jLabel5.setText("ID");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(84, 142, 211));
        jLabel6.setText("Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 180, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(84, 142, 211));
        jLabel7.setText("Email");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 180, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(84, 142, 211));
        jLabel8.setText("City");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 180, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(84, 142, 211));
        jLabel10.setText("Job Type");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 180, -1));

        ADDAPPLICANT.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        ADDAPPLICANT.setForeground(new java.awt.Color(84, 142, 211));
        ADDAPPLICANT.setText(" Add Applicant");
        ADDAPPLICANT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDAPPLICANTActionPerformed(evt);
            }
        });
        jPanel1.add(ADDAPPLICANT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 600, 240, 80));

        UPDATEApplicant.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        UPDATEApplicant.setForeground(new java.awt.Color(84, 142, 211));
        UPDATEApplicant.setText("Update Applicant ");
        UPDATEApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATEApplicantActionPerformed(evt);
            }
        });
        jPanel1.add(UPDATEApplicant, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 600, 240, 80));

        idtxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtxtActionPerformed(evt);
            }
        });
        jPanel1.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 190, 40));
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 190, 40));
        jPanel1.add(CVtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 520, 190, 40));

        jTable1Applicant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Email", "Address", "Job Type", "CV"
            }
        ));
        jScrollPane1.setViewportView(jTable1Applicant);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 1050, 520));

        CV.setText("Upload CV");
        CV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVActionPerformed(evt);
            }
        });
        jPanel1.add(CV, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 110, 50));

        jobcomb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HR", "Marketing ", "Finannce", "Accounting", "Production", "IT", "Customer Service", "sales", "Mangement", "Medicine" }));
        jobcomb.setSelectedItem("IT");
        jobcomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobcombActionPerformed(evt);
            }
        });
        jPanel1.add(jobcomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 190, 40));

        Citycomb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cairo", "Alex", "BaniSwif", "Minia", "Giza", "Assuit", "Sohag", "Qena", "New Valley", "Luxor", "Aswan", "Fayoum", "Tanta", "Other..." }));
        Citycomb.setSelectedItem("Sohag");
        Citycomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitycombActionPerformed(evt);
            }
        });
        jPanel1.add(Citycomb, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 190, 40));

        SHOWALLAPPLICANT.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        SHOWALLAPPLICANT.setForeground(new java.awt.Color(84, 142, 211));
        SHOWALLAPPLICANT.setText("Show All Applicants");
        SHOWALLAPPLICANT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWALLAPPLICANTActionPerformed(evt);
            }
        });
        jPanel1.add(SHOWALLAPPLICANT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 600, 260, 80));

        SHOWAPPLICANTBYID.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        SHOWAPPLICANTBYID.setForeground(new java.awt.Color(84, 142, 211));
        SHOWAPPLICANTBYID.setText("Search  For Applicant");
        SHOWAPPLICANTBYID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWAPPLICANTBYIDActionPerformed(evt);
            }
        });
        jPanel1.add(SHOWAPPLICANTBYID, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 600, 270, 80));

        DeleteApplicant2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        DeleteApplicant2.setForeground(new java.awt.Color(84, 142, 211));
        DeleteApplicant2.setText("Delete Applicant ");
        DeleteApplicant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteApplicant2ActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteApplicant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 600, 230, 80));
        jPanel1.add(mailtxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 190, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1560, 790));

        setSize(new java.awt.Dimension(1577, 895));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UPDATEApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATEApplicantActionPerformed

        int id = Integer.parseInt(idtxt.getText());
        String name = nametxt.getText();
        String mail = mailtxt1.getText();
        city = (String) Citycomb.getSelectedItem();
        job = (String) jobcomb.getSelectedItem();

//        Applicant applicant = new Applicant();
        Applicant applicant = new Applicant(id, name, mail, cv, job, city);
        try {
            applicantBLL.updateApplicant(applicant);
//               st = con.createStatement();
//        ResultSet res  =    st.executeQuery("select * from tblApplicant ");
//        jTable1Applicant.setModel(DbUtils.resultSetToTableModel(res));
//            
            JOptionPane.showMessageDialog(null, "اي خدمة يقمر");

        } catch (Exception e) {
            e.printStackTrace();
        }
//        idtxt.setText("");
//            nametxt.setText("");
//            mailtxt.setText("");
//            Citycomb.setSelectedItem(null);
//            jobcomb.setSelectedItem(null);
    }//GEN-LAST:event_UPDATEApplicantActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setVisible(false);
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ADDAPPLICANTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDAPPLICANTActionPerformed
        String idText = idtxt.getText().trim();
//// validiation ID 
        if (!idText.matches("\\d+") || idText.startsWith("0") || idText.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Id (digits only) which cannot start with 0 and cannot be empty  ");
            return; // Stop execution if ID is invalid
        } else if ((applicantBLL.isApplicantIDValid(Integer.parseInt(idText)))) {
            JOptionPane.showMessageDialog(null, "Please enter a different Id. This Id already exists.");
            return;
        }
        int id = Integer.parseInt(idText);
        

        String name = nametxt.getText();
         // Validate Name field
        if (!name.matches("[a-zA-Z\\s]+") || name.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid name (alphabetical characters and spaces only and cannot be empty)");
            return; // Stop execution if name is invalid
        }
        /////////
        String mail = mailtxt1.getText();
         if (mail.isEmpty() || !mail.contains("@")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Email which must contain \"@\"");
            return; // Stop execution if phone number is invalid
        }
         ///////
         
      if (Citycomb.getSelectedItem() == null) {
          JOptionPane.showMessageDialog(null, "please select Your City ");
     
      }
      if (jobcomb.getSelectedItem() == null) {
          JOptionPane.showMessageDialog(null, "please select Your Job  ");
     
      }
//        if (CV.path) {
//          JOptionPane.showMessageDialog(null, "please select Your Job  ");
//     
//      }
//      
            
        Applicant applicant = new Applicant(id, name, mail, cv, job, city);

        try {
            applicantBLL.addApplicant(applicant);

        } catch (SQLException e) {
            e.printStackTrace();
        }
        idtxt.setText("");
        nametxt.setText("");
        CVtxt.setText("");
        mailtxt1.setText("");
        //Citycomb.setSelectedItem(null);
        //jobcomb.setSelectedItem(null);
       }//GEN-LAST:event_ADDAPPLICANTActionPerformed

    private void CVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVActionPerformed

        JFileChooser img = new JFileChooser();
        int i = img.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            File f = img.getSelectedFile();
            String path = f.getPath();
            String cv = f.getName();
            CVtxt.setText(cv);
            FileOutputStream fos = null;
            FileInputStream fis = null;
            try {
                fis = new FileInputStream(path);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            }
            // C:\Users\MhMd Glaal\Documents\NetBeansProjects\ImageDisplayExample\src\ImageDisplayExample\Images
            try {
                fos = new FileOutputStream("C:/Users/m/Desktop/Imagesss" + cv);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            }
            byte[] buffer = new byte[1024];
            int read = 0;
            try {
                while ((read = fis.read(buffer)) != -1) {
                    try {
                        fos.write(buffer, 0, read);
                    } catch (IOException ex) {
                        Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            } catch (IOException ex) {
                Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            }

            try {
                fis.close();
                fos.close();
            } catch (IOException ex) {
                Logger.getLogger(User.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_CVActionPerformed

    private void CitycombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitycombActionPerformed
           city = (String)Citycomb.getSelectedItem();
    }//GEN-LAST:event_CitycombActionPerformed

    private void jobcombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobcombActionPerformed
           job = (String) jobcomb.getSelectedItem();

    }//GEN-LAST:event_jobcombActionPerformed

    private void SHOWALLAPPLICANTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWALLAPPLICANTActionPerformed
        try {

            st = con.createStatement();
            ResultSet res = st.executeQuery("select * from tblApplicant ");
            jTable1Applicant.setModel(DbUtils.resultSetToTableModel(res));
            JOptionPane.showMessageDialog(null, "show all applicant");
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_SHOWALLAPPLICANTActionPerformed

    private void SHOWAPPLICANTBYIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWAPPLICANTBYIDActionPerformed

        Applicant applicant = new Applicant();
        try {
            int id = Integer.parseInt(idtxt.getText());
            applicant = applicantBLL.ShowApplicantById(id);
            nametxt.setText(applicant.getName());
            mailtxt1.setText(applicant.getEmail());
            Citycomb.setSelectedItem(applicant.getCity());
            jobcomb.setSelectedItem(applicant.getJob());

            JOptionPane.showMessageDialog(null, "Messiiiiiiiiii");

        } catch (Exception e) {
            e.printStackTrace();
        }
//            
//            nametxt.setText("");
//            mailtxt.setText("");
//            Citycomb.setSelectedItem(null);
//            jobcomb.setSelectedItem(null);
    }//GEN-LAST:event_SHOWAPPLICANTBYIDActionPerformed

    private void DeleteApplicant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteApplicant2ActionPerformed
        int id = Integer.parseInt(idtxt.getText());
        String name = nametxt.getText();
        String mail = CVtxt.getText();
        Applicant applicant = new Applicant(id, name, mail, cv, job, city);
        try {
            applicantBLL.deleteApplicant(applicant.getId());
            JOptionPane.showMessageDialog(null, "Siiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiu");
//         st = con.createStatement();
//        ResultSet res  =    st.executeQuery("select * from tblApplicant ");
//        jTable1Applicant.setModel(DbUtils.resultSetToTableModel(res));

        } catch (Exception e) {
        }
        idtxt.setText("");
        nametxt.setText("");
        CVtxt.setText("");
        Citycomb.setSelectedItem(null);
        jobcomb.setSelectedItem(null);


    }//GEN-LAST:event_DeleteApplicant2ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            String url = "jdbc:ucanaccess://E:/REC-AGENCY1.accdb";
            con = DriverManager.getConnection(url);

            st = con.createStatement();
            ResultSet res = st.executeQuery("select * from tblApplicant");

            jTable1Applicant.setModel(DbUtils.resultSetToTableModel(res));

        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_formWindowActivated

    private void idtxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtxtActionPerformed
//String id = idtxt.getText().trim();
//if (id.length() == 0 || id.equals("")) {
//    JOptionPane.showMessageDialog(null, "ID cannot be empty.");
//    return  ;

//}
//if (id.length() < 4 || id.length() > 7) {
//    JOptionPane.showMessageDialog(null, "ID must be between 4 and 7 digits.");
//    
//}
//if (!id.matches("\\d+")) {
//    JOptionPane.showMessageDialog(null, "ID must contain only numbers.");
//}
// If all validations pass
//String id = idtxt.getText().trim();
//    if (id.length() == 0 || id.equals("")) {
//        JOptionPane.showMessageDialog(null, "ID cannot be empty.");
//        return ;
//    }
//    if (id.length() < 4 || id.length() > 7) {
//        JOptionPane.showMessageDialog(null, "ID must be between 4 and 7 digits.");
//        return;
//    }
//    if (!id.matches("\\d+")) {
//        JOptionPane.showMessageDialog(null, "ID must contain only numbers.");
//        return;
//    }
        // If all validations pass, perform further actions
        // ...

    }//GEN-LAST:event_idtxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Are you sure ?", "Project Exit ", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Applicant_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Applicant_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Applicant_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Applicant_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Applicant_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDAPPLICANT;
    private javax.swing.JButton CV;
    private javax.swing.JTextField CVtxt;
    private javax.swing.JComboBox<String> Citycomb;
    private javax.swing.JButton DeleteApplicant2;
    private javax.swing.JButton SHOWALLAPPLICANT;
    private javax.swing.JButton SHOWAPPLICANTBYID;
    private javax.swing.JButton UPDATEApplicant;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1Applicant;
    private javax.swing.JComboBox<String> jobcomb;
    private javax.swing.JTextField mailtxt1;
    private javax.swing.JTextField nametxt;
    // End of variables declaration//GEN-END:variables
}
