/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hiring;

import java.sql.*;
import java.awt.*;
import java.awt.print.PrinterException;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.text.*;
import net.proteanit.sql.DbUtils;

import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
//import com.sun.jdi.connect.spi.Connection;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author EL10_gazy
 */
public class Home extends JFrame {

    Connection connection;
    private JFrame hiring;
   

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * Creates new form Home
     */
    public Home(Connection con) {
        this();
        this.connection = con;
    }

    public Home() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        AddCompany = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Applicant = new javax.swing.JButton();
        AddJob = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(149, 197, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AddCompany.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        AddCompany.setForeground(new java.awt.Color(84, 142, 211));
        AddCompany.setText(" Company");
        AddCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCompanyActionPerformed(evt);
            }
        });
        jPanel5.add(AddCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 570, -1, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hiring/app.jpg"))); // NOI18N
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, 470));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hiring/company.jpg"))); // NOI18N
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hiring/uppda.jpg"))); // NOI18N
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 40, -1, 460));

        Applicant.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        Applicant.setForeground(new java.awt.Color(84, 142, 211));
        Applicant.setText(" Applicant");
        Applicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApplicantActionPerformed(evt);
            }
        });
        jPanel5.add(Applicant, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, -1, -1));

        AddJob.setFont(new java.awt.Font("Sitka Subheading", 1, 36)); // NOI18N
        AddJob.setForeground(new java.awt.Color(84, 142, 211));
        AddJob.setText("Job");
        AddJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddJobActionPerformed(evt);
            }
        });
        jPanel5.add(AddJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 570, 150, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 1380, 630));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(84, 142, 211));
        jLabel2.setText("JOB FINDER");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, 220, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1450, 500));

        jPanel3.setBackground(new java.awt.Color(84, 142, 211));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 1450, 260));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1580, 850));

        setSize(new java.awt.Dimension(1590, 845));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AddJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddJobActionPerformed
        JobDAL jobDAL=new JobDAL(connection);
        JobBLL jobBLL=new JobBLL(jobDAL);
        Job_Frame jobframe = new Job_Frame(jobBLL); 
        this.setVisible(false);
        jobframe.setVisible(true);

    }//GEN-LAST:event_AddJobActionPerformed

    private void ApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ApplicantActionPerformed

        ApplicantDAL applicantDAL = new ApplicantDAL(connection);
        ApplicantBLL applicantBLL = new ApplicantBLL(applicantDAL);
        Applicant_Frame applicantframe = new Applicant_Frame(connection, applicantBLL);

        this.setVisible(false);
        applicantframe.setVisible(true);


            }//GEN-LAST:event_ApplicantActionPerformed

    private void AddCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCompanyActionPerformed
        CompanyDAL companyDAL = new CompanyDAL(connection);
        CompanyBLL companyBLL = new CompanyBLL(companyDAL);
        COMPANYY_Frame companyframe = new COMPANYY_Frame(companyBLL);
        this.setVisible(false);
        companyframe.setVisible(true);

    }//GEN-LAST:event_AddCompanyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCompany;
    private javax.swing.JButton AddJob;
    private javax.swing.JButton Applicant;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
