/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hiring;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author EL10_gazy
 */
public class Job_Frame extends javax.swing.JFrame {
//   Connection conjob  ;
//     Statement stjob ;
//     PreparedStatement pst ; 

    private Connection con;
    private Statement st;

    private JobBLL jobBll;

    public Job_Frame(JobBLL jobBLL) {
        this();
        this.jobBll = jobBLL;

    }

    public Job_Frame() {
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ddd = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        UPDATECOMPANY = new javax.swing.JButton();
        ADDJOB = new javax.swing.JButton();
        titletxt = new javax.swing.JTextField();
        JobSkillstxt = new javax.swing.JTextField();
        Avilabletxt = new javax.swing.JTextField();
        idtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableJob = new javax.swing.JTable();
        DELETEJOB = new javax.swing.JLabel();
        Com = new javax.swing.JLabel();
        SEARCHFORJOB = new javax.swing.JButton();
        COMPtxt = new javax.swing.JTextField();
        DELETECOMPANY1 = new javax.swing.JButton();
        SHOWALLAVILABLEJOB1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(84, 142, 211));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Updating Available Jobs");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 27, 505, -1));

        jButton1.setBackground(new java.awt.Color(84, 142, 211));
        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Home");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 10, -1, 50));

        Exit.setBackground(new java.awt.Color(84, 142, 211));
        Exit.setFont(new java.awt.Font("Segoe UI Semibold", 2, 36)); // NOI18N
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jPanel1.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(84, 142, 211));
        jLabel5.setText("Job Title");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(84, 142, 211));
        jLabel8.setText("Job Skills");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 320, 50));

        ddd.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        ddd.setForeground(new java.awt.Color(84, 142, 211));
        ddd.setText("Job  Available");
        jPanel2.add(ddd, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 240, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(84, 142, 211));
        jLabel11.setText("Job  ID");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 180, 50));

        UPDATECOMPANY.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        UPDATECOMPANY.setForeground(new java.awt.Color(84, 142, 211));
        UPDATECOMPANY.setText("Update Company");
        UPDATECOMPANY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UPDATECOMPANYActionPerformed(evt);
            }
        });
        jPanel2.add(UPDATECOMPANY, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 600, 230, 70));

        ADDJOB.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        ADDJOB.setForeground(new java.awt.Color(84, 142, 211));
        ADDJOB.setText("Add Job");
        ADDJOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDJOBActionPerformed(evt);
            }
        });
        jPanel2.add(ADDJOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 210, 70));

        titletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titletxtActionPerformed(evt);
            }
        });
        jPanel2.add(titletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 190, 40));
        jPanel2.add(JobSkillstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 190, 40));

        Avilabletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvilabletxtActionPerformed(evt);
            }
        });
        jPanel2.add(Avilabletxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 400, 190, 40));
        jPanel2.add(idtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 190, 40));

        jTableJob.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Title", "Departement", "Location", "Company Name", "Job Details", "Job Hours"
            }
        ));
        jScrollPane1.setViewportView(jTableJob);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 100, 860, 470));

        DELETEJOB.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        DELETEJOB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(84, 142, 211), 6));
        jPanel2.add(DELETEJOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1510, 550));

        Com.setFont(new java.awt.Font("Segoe UI Historic", 1, 36)); // NOI18N
        Com.setForeground(new java.awt.Color(84, 142, 211));
        Com.setText("Comp Name");
        jPanel2.add(Com, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 220, -1));

        SEARCHFORJOB.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        SEARCHFORJOB.setForeground(new java.awt.Color(84, 142, 211));
        SEARCHFORJOB.setText("Search For Job");
        SEARCHFORJOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEARCHFORJOBActionPerformed(evt);
            }
        });
        jPanel2.add(SEARCHFORJOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 260, 70));
        jPanel2.add(COMPtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 510, 190, 40));

        DELETECOMPANY1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        DELETECOMPANY1.setForeground(new java.awt.Color(84, 142, 211));
        DELETECOMPANY1.setText("Delete Company");
        DELETECOMPANY1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETECOMPANY1ActionPerformed(evt);
            }
        });
        jPanel2.add(DELETECOMPANY1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 600, 210, 70));

        SHOWALLAVILABLEJOB1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        SHOWALLAVILABLEJOB1.setForeground(new java.awt.Color(84, 142, 211));
        SHOWALLAVILABLEJOB1.setText("Show All  Available Job ");
        SHOWALLAVILABLEJOB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SHOWALLAVILABLEJOB1ActionPerformed(evt);
            }
        });
        jPanel2.add(SHOWALLAVILABLEJOB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 600, 250, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1549, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        JFrame frameJOP = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frameJOP, "Are you sure ?", "Project Exit ", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
     }//GEN-LAST:event_ExitActionPerformed

    private void ADDJOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDJOBActionPerformed
        String id =idtxt.getText().trim();
       
         if (id.startsWith("0")|| id.isEmpty()||!id.matches("\\d+"))  {
            JOptionPane.showMessageDialog(null, "Please enter a valid Id (digits only) which cannot start with 0 and cannot be empty  ");
            return; // Stop execution if ID is invalid
        } else if (jobBll.isJobIDValid(Integer.parseInt(id))) {
            JOptionPane.showMessageDialog(null, "Please enter a different Id. This Id already exists.");
            
            return;
            
           
        }
           int ID = Integer.parseInt(id);
           
           ////////////////
        String title = titletxt.getText();
         if (!title.matches("[a-zA-Z\\s]+") || title.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please enter a valid Title (alphabetical characters and spaces only).");
            return; // Stop execution if name is invalid
        }
               ////////////////
        String Jobskills = JobSkillstxt.getText();
         
         if (Jobskills.isEmpty() || !Jobskills.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid JobSkills , must be (alphabetical characters and spaces only) ");
            return; // Stop execution if phone number is invalid
        }
String avilablejob =Avilabletxt.getText().trim(); 
 if (avilablejob.isEmpty()  || !avilablejob.matches("\\d+"))  {
            JOptionPane.showMessageDialog(null, "Please enter a valid avilablejob (digits only) which cannot be empty  ");
            return;
 }
 
        int JOBAVILABLE  = Integer.parseInt(id);
        ////////////validaion 
         String CompName  = JobSkillstxt.getText();
         
         if (CompName.isEmpty() || !CompName.matches("[a-zA-Z\\s]+")) {
            JOptionPane.showMessageDialog(null, "Please enter a valid title , must be (alphabetical characters and spaces only) ");
            return; // Stop execution if phone number is invalid
        }
        

        Job ff = new Job(ID, title, Jobskills, JOBAVILABLE, CompName);
        try {
            jobBll.addJob(ff);
            //    JOptionPane.showMessageDialog(null, "   كل الناس بتقول يارب ");

        } catch (Exception e) {
            e.printStackTrace();
            idtxt.setText("");
            titletxt.setText("");
            JobSkillstxt.setText("");
            Avilabletxt.setText("");
            COMPtxt.setText("");

        }
    }//GEN-LAST:event_ADDJOBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        Home home = new Home();
        home.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void titletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titletxtActionPerformed

    private void SEARCHFORJOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEARCHFORJOBActionPerformed
        Job job = new Job();

        int ID = Integer.parseInt(idtxt.getText());
        try {

            job = jobBll.showJobById(ID);
            // companyreftxt.setText(company.getRef());
            titletxt.setText(job.getJOBTitle());
            JobSkillstxt.setText(job.getJOBSkill());
            Avilabletxt.setText(job.getJOBAvailable() + "");

            // Avilabletxt.setText(job.getJOBAvailable()) ;
            COMPtxt.setText(job.getC_Name());

            //  int jobavailable = Integer.parseInt(Avilabletxt.);
            //  JOptionPane.showMessageDialog(null, "Messiiiiiiiiii");
            // Avilabletxt.setTe
            // int AvilableJob = Integer.parseInt(Avilabletxt.getText());
        } catch (Exception e) {
            e.printStackTrace();
        }


            }//GEN-LAST:event_SEARCHFORJOBActionPerformed

    private void UPDATECOMPANYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UPDATECOMPANYActionPerformed

        Job job = new Job();
        try {
            int id = Integer.parseInt(idtxt.getText());
            job = jobBll.showJobById(id);
            titletxt.setText(job.getJOBTitle());
            JobSkillstxt.setText(job.getJOBSkill());

         //int  AvilableJob = Integer.parseInt(Avilabletxt.getText());
int AvilableJob = Integer.parseInt(Avilabletxt.getText());
           
// Avilabletxt.setText(job.getJOBAvailable() + "");
            COMPtxt.setText(job.getC_Name());
            

            //   JOptionPane.showMessageDialog(null, "Messiiiiiiiiii");
        } catch (Exception e) {
            e.printStackTrace();
        }


    }//GEN-LAST:event_UPDATECOMPANYActionPerformed

    private void DELETECOMPANY1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETECOMPANY1ActionPerformed
        int id = Integer.parseInt(idtxt.getText());

        Job job = new Job(id);
        try {

            jobBll.deleteJob(id);

//        JOptionPane.showMessageDialog(null, "Messiiiiiiiiii");
        } catch (Exception e) {
            e.printStackTrace();
        }
        idtxt.setText("");
    }//GEN-LAST:event_DELETECOMPANY1ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try {
            String url = "jdbc:ucanaccess://E:/REC-AGENCY1.accdb";
            con = DriverManager.getConnection(url);

            st = con.createStatement();
            ResultSet res = st.executeQuery("select * from tblJob");

            jTableJob.setModel(DbUtils.resultSetToTableModel(res));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowActivated

    private void SHOWALLAVILABLEJOB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SHOWALLAVILABLEJOB1ActionPerformed
        try {

            st = con.createStatement();
            ResultSet res = st.executeQuery("select * from tblJob ");
            jTableJob.setModel(DbUtils.resultSetToTableModel(res));
            JOptionPane.showMessageDialog(null, "show all Job");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_SHOWALLAVILABLEJOB1ActionPerformed

    private void AvilabletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvilabletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AvilabletxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Job_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Job_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Job_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Job_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Job_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDJOB;
    private javax.swing.JTextField Avilabletxt;
    private javax.swing.JTextField COMPtxt;
    private javax.swing.JLabel Com;
    private javax.swing.JButton DELETECOMPANY1;
    private javax.swing.JLabel DELETEJOB;
    private javax.swing.JButton Exit;
    private javax.swing.JTextField JobSkillstxt;
    private javax.swing.JButton SEARCHFORJOB;
    private javax.swing.JButton SHOWALLAVILABLEJOB1;
    private javax.swing.JButton UPDATECOMPANY;
    private javax.swing.JLabel ddd;
    private javax.swing.JTextField idtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableJob;
    private javax.swing.JTextField titletxt;
    // End of variables declaration//GEN-END:variables
}
